name: Docker Image CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag nexius/docker-react --file Dockerfile.dev .
      
    - name: Run test
      run: docker run -e CI=true nexius/docker-react npm run test -- --coverage
